site_name: Buyers Documentation
theme:
  name: material
  logo: img/logo.svg
  favicon: img/logo.svg
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  palette:
    scheme: slate # тёмная тема по умолчанию
    primary: orange
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/extra.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox

nav:
  - Главная: index.md
  - Кампании в AIO: 
      - Как попасть в кампанию и что внутри: aio/campaign-desc.md
      - Как сгенерировать ссылку для залива: aio/how-to-generate-link.md
  - Регламенты для задач: aio/regulations.md
  # - Добавление новой кампании: aio/new-campaign.md
  # - Добавление нового вайта: aio/how-to-add-white.md
  # - AIO (Crypto):
  #     - Offers:
  #         - Adding new offer: aio-crypto/offers/new-offer.md
  #         - Offer adaptaion for AIO (google): aio-crypto/offers/offer-adapt-google.md
  #     - Whites:
  #         - Adding new white: aio-crypto/whites/new-white.md
  #         - White adaptation for AIO: aio-crypto/whites/white-adapt.md
  #     - Campaigns:
  #         - Creating new campaign: aio-crypto/campaigns/new-campaign.md
  #         - Adding Buyer UTM for campaigns: aio/users/buyer-utm.md
  #     - Domains:
  #         - Domains initial path: aio-crypto/domains/domains-path.md
  #     - Flows: aio-crypto/flow/flow-explanation.md
